export const ko = {
  permissionNeeded: '권한 확인',
  practiceDetails: '연습 음성은 어떻게 처리되나요?',
  mode: '녹음 방식',
  featureDescriptions: [
    '설정 → 일반에서 소리 줄이기를 켜고 녹음 중 볼륨을 지정하세요.',
    '설정 → 사전에 자주 쓰는 이름·용어를 추가하고, 교정 규칙으로 잘못 인식한 표현을 바꾸세요.',
    '설정 → 일반에서 Ask 단축키를 지정하세요. 받아쓰기 대신 AI 답변을 확인하는 기능입니다.',
    '설정 → 일반에서 결과 복사 단축키를 지정하세요. 복사 창이 있을 때 키를 누르면 결과가 복사됩니다.',
  ],
  mobileTitle: 'Android에서도 사용하려면',
  mobileSteps: [
    '모바일 연결 메뉴에서 내부 IP와 포트를 지정하고 연결을 켜세요.',
    '같은 네트워크 또는 WireGuard에 연결한 Android 앱에 표시된 서버 주소를 입력하세요.',
    'Android에서 H 키보드를 활성화하고 사용하세요. 컴퓨터의 H 앱은 켜 두어야 합니다.',
  ],
  cancelTip: '잘못 녹음했다면 녹음 표시의 취소 버튼을 누르세요. 결과를 입력하지 않고 끝냅니다.',
  testPassed: '연결 테스트를 통과했습니다.',
  close: '저장하고 닫기',
  skip: '연습 건너뛰기',
  reopen: '홈 화면 또는 설정 → 정보에서 사용 방법을 다시 볼 수 있습니다.',
  name: '시작 가이드',
  revisit: '사용 방법 다시 보기',
  step: '단계',
  back: '이전',
  next: '계속',
  later: '저장하고 나중에 계속',
  finish: '완료',
  saving: '저장 중…',
  details: '직접 설정하기',
  begin: '시작',
  speechTitle: '음성 인식',
  aiTitle: '문장 다듬기',
  change: '변경',
  configure: '설정',
  notSelected: '모델을 선택해 주세요',
  savedSetup: '설정됨',
  setupNeeded: '설정 필요',
  setupReady: '현재 설정으로 연습할 수 있습니다.',
  aiOptional: '연결 테스트로 확인할 수 있습니다. 다듬기는 선택 사항입니다.',
  permissionHint:
    '마이크는 첫 녹음 때 허용하세요. 다른 앱 입력 권한은 단축키의 변경 메뉴에서 확인할 수 있습니다.',
  moreTips: '다른 기능 알아보기',
  titles: [
    '말하면, 입력됩니다.',
    '준비를 확인하세요.',
    '직접 말해 보세요.',
    '이제 입력칸에서 사용하세요.',
  ],
  subtitles: [
    '입력칸을 클릭하고 단축키를 누르세요.',
    '이미 설정했다면 그대로 계속하세요.',
    '버튼을 누르고 아래 문장을 읽어 보세요.',
    '필요할 때 단축키를 누르면 됩니다.',
  ],
  labels: ['사용 방법', '준비', '연습', '완료'],
  record: '말하기',
  transcribe: '글로 바꾸기',
  polish: '선택해서 다듬기',
  insert: '입력하기',
  exampleLabel: '입력 예시',
  exampleRaw: '어 설정 그 화면에 취소 버튼 좀 추가해 줘',
  examplePolished: '설정 화면에 취소 버튼을 추가해 줘.',
  welcomeText: '메신저, 문서, 개발 도구의 입력칸에서 사용할 수 있습니다.',
  local: '이 컴퓨터에서 인식',
  localDesc:
    '모델을 한 번 다운로드하면 인터넷 없이도 음성을 글로 바꿉니다. 별도 STT 서버는 필요 없습니다.',
  external: '기존 API 사용',
  externalDesc:
    '사용 중인 음성 인식 서비스를 연결합니다. 제공자에 따라 주소나 API 키가 필요합니다.',
  modelHelp:
    '가볍게 시작하려면 Whisper Base. Qwen은 메모리 여유에 따라 0.6B 또는 1.7B를 선택하세요. 호환 Mac에서는 MLX GPU를 자동 사용합니다.',
  ready: '선택한 모델이 준비됐습니다',
  modelNeeded: '음성 인식의 설정을 열어 모델을 선택하세요.',
  testNeeded: '설정을 입력하고 연결 테스트를 통과해 주세요.',
  polishOn: 'AI로 다듬기',
  polishDesc: 'Ollama 또는 LLM API를 연결합니다. 말버릇과 어색한 문장을 정리할 수 있습니다.',
  polishOff: '받아쓰기만 사용',
  polishOffDesc: '인식한 문장을 그대로 사용합니다. 나중에 설정에서 켤 수 있습니다.',
  polishHelp:
    'Ollama는 별도로 설치하고 모델을 준비해야 합니다. 외부 API를 선택하면 텍스트가 해당 제공자로 전송됩니다.',
  hotkey: '단축키와 권한',
  hold: '키를 누른 채 말하고, 놓으면 종료합니다.',
  toggle: '한 번 눌러 시작하고, 다시 눌러 종료합니다.',
  controlHelp: '연습에서는 화면의 녹음 버튼을 사용합니다. 평소에는 아래 단축키를 사용하세요.',
  hotkeySettings: '단축키와 입력 방식 설정',
  practiceExample: '“설정 화면에 취소 버튼을 추가해 주세요.”',
  practicePrivacy:
    '선택한 음성 인식·AI로 처리합니다. 다른 앱에 입력하거나 기록에 저장하지 않습니다.',
  start: '녹음 시작',
  stop: '끝내고 확인',
  cancel: '취소',
  preparing: '마이크 준비 중…',
  recording: '듣고 있어요 · 최대 15초',
  processing: '음성을 글로 바꾸고 있어요… 처음에는 모델 준비에 시간이 걸릴 수 있습니다.',
  cancelled: '연습을 취소했습니다. 다시 시작할 수 있습니다.',
  raw: '음성 인식 원문',
  polished: '사용할 문장',
  processingTime: '전체 처리 시간',
  empty: '인식된 문장이 없습니다. 마이크와 언어 설정을 확인하고 다시 시도해 주세요.',
  unsupported:
    '이 화면의 직접 연습은 내장 STT와 Whisper 호환 API를 지원합니다. 다른 제공자는 연습을 건너뛰고 평소 단축키로 사용해 주세요.',
  untested: '최대 15초 · 결과는 여기에만 표시됩니다.',
  practiced: '실제 음성 처리 결과를 확인했습니다.',
  retry: '다시 녹음',
  tips: [
    '입력칸을 클릭한 뒤 단축키로 말하세요.',
    '다른 앱으로 이동했다면 복사 창에서 결과를 가져오세요.',
    'Mac에서는 창을 닫아도 메뉴 막대에 남습니다. 완전히 끝내려면 종료를 선택하세요.',
    '모바일 연결 메뉴에서 Android 키보드와 연결할 수 있습니다.',
  ],
  features: [
    '녹음 중 다른 소리 줄이기',
    '사전으로 개발 용어·이름 교정',
    'Ask로 말해서 질문하기',
    '복사 창 전용 단축키',
  ],
  featuresTitle: '익숙해지면 이런 기능도 사용해 보세요',
  featuresHelp: '설정 → 일반 / 사전에서 필요한 기능만 선택하세요. Ask에는 LLM 연결이 필요합니다.',
  noTest: '녹음 연습을 건너뛰었습니다. 나중에 다시 해볼 수 있습니다.',
}
export const en: typeof ko = {
  permissionNeeded: 'Check permission',
  practiceDetails: 'How is this recording processed?',
  mode: 'Recording mode',
  featureDescriptions: [
    'Enable audio ducking in General settings and choose the volume while recording.',
    'Add names and terms in Dictionary. Use correction rules to replace frequently misrecognized expressions.',
    'Set an Ask shortcut in General settings to ask AI a question instead of dictating text.',
    'Set a result-copy shortcut in General settings. Press it when the copy window appears to copy its text.',
  ],
  mobileTitle: 'Use your Android keyboard too',
  mobileSteps: [
    'In Mobile connection, choose your local IP and port and enable the connection.',
    'Connect Android to the same network or WireGuard, then enter the displayed server address in the Android app.',
    'Enable the H keyboard on Android. Keep the desktop H app running while using it.',
  ],
  cancelTip:
    'Made a mistake? Use the cancel button in the recording indicator to finish without inserting text.',
  testPassed: 'Connection test passed.',
  close: 'Save and close',
  skip: 'Skip practice',
  reopen: 'Reopen this guide from Home or Settings → About.',
  name: 'Getting started',
  revisit: 'Open the getting-started guide',
  step: 'Step',
  back: 'Back',
  next: 'Continue',
  later: 'Save and continue later',
  finish: 'Done',
  saving: 'Saving…',
  details: 'Configure provider',
  begin: 'Start',
  speechTitle: 'Speech recognition',
  aiTitle: 'Text polish',
  change: 'Change',
  configure: 'Set up',
  notSelected: 'Choose a model',
  savedSetup: 'Configured',
  setupNeeded: 'Needs setup',
  setupReady: 'Continue to try your current setup.',
  aiOptional: 'Use the connection test to check it. Polish is optional.',
  permissionHint:
    'Allow microphone access when recording. Open shortcut settings to check permission for typing into other apps.',
  moreTips: 'Explore more features',
  titles: [
    'Speak. Your words appear.',
    'Check your setup.',
    'Give it a try.',
    'Use it in any text field.',
  ],
  subtitles: [
    'Click a text field and press your shortcut.',
    'Already set up? Keep your settings and continue.',
    'Press record and read the sentence below.',
    'Press your shortcut whenever you need it.',
  ],
  labels: ['How it works', 'Setup', 'Practice', 'Done'],
  record: 'Speak',
  transcribe: 'Transcribe',
  polish: 'Optional polish',
  insert: 'Insert',
  exampleLabel: 'Example',
  exampleRaw: 'um add a cancel button to the settings screen please',
  examplePolished: 'Please add a cancel button to the settings screen.',
  welcomeText: 'Works in your messages, documents, and development tools.',
  local: 'Recognize on this computer',
  localDesc: 'Download a model once, then transcribe offline. No separate STT server is needed.',
  external: 'Use an existing API',
  externalDesc: 'Connect your speech provider using its address or API key.',
  modelHelp:
    'Start with Whisper Base for a lighter model. Choose Qwen 0.6B or 1.7B according to available memory. Compatible Macs use MLX GPU automatically.',
  ready: 'The selected model is ready',
  modelNeeded: 'Download a model and choose “Use this model”.',
  testNeeded: 'Configure the provider and pass its connection test.',
  polishOn: 'Polish with AI',
  polishDesc: 'Connect Ollama or an LLM API to clean up filler words and awkward sentences.',
  polishOff: 'Just transcribe',
  polishOffDesc: 'Keep the recognized words. You can enable polish later.',
  polishHelp:
    'Ollama and its model must be installed separately. External APIs receive the text you ask them to process.',
  hotkey: 'Shortcut & permissions',
  hold: 'Hold the key while speaking. Release it to finish.',
  toggle: 'Press once to start and again to finish.',
  controlHelp: 'Practice uses an on-screen recording button. Use this shortcut in everyday apps.',
  hotkeySettings: 'Shortcut and input settings',
  practiceExample: '“Please add a cancel button to the settings screen.”',
  practicePrivacy:
    'Records for up to 15 seconds using your selected speech and AI providers. Results stay in this preview and are not added to history.',
  start: 'Start recording',
  stop: 'Stop and preview',
  cancel: 'Cancel',
  preparing: 'Preparing microphone…',
  recording: 'Listening · up to 15 seconds',
  processing: 'Turning your speech into text… The first run may need time to prepare the model.',
  cancelled: 'Practice cancelled. You can try again.',
  raw: 'Recognized words',
  polished: 'Text to use',
  processingTime: 'Total processing time',
  empty: 'No words were recognized. Check your microphone and language, then try again.',
  unsupported:
    'This preview supports built-in STT and Whisper-compatible APIs. For other providers, skip practice and use your usual shortcut.',
  untested: 'Up to 15 seconds · Results appear only here.',
  practiced: 'A real speech result was received.',
  retry: 'Record again',
  tips: [
    'Click a text field and speak with your shortcut.',
    'If you switch apps, retrieve the result from the copy window.',
    'On Mac, closing the window leaves the menu bar app running. Choose Quit to stop it.',
    'Connect your Android keyboard from the Mobile connection menu.',
  ],
  features: [
    'Reduce other audio while recording',
    'Correct names and terms with the dictionary',
    'Ask questions with your voice',
    'Set a shortcut for the copy window',
  ],
  featuresTitle: 'Explore these when you are comfortable',
  featuresHelp:
    'Choose what you need in General settings and Dictionary. Ask requires an LLM connection.',
  noTest: 'Practice skipped. You can return and try a recording later.',
}
